/** 
 * Objective: 
 * To show case the output generated by the dlerror() function
 * So we'll only write the add() function into the server program
 * and avoid writing the subtraction program and we'll call the 
 * subtraction program from the client program
 */

int add(int a, int b)
{
	return a + b;
}
